[package]
name = "iss-scale-widget"
version = "0.1.0"
description = "Compact desktop widget for the Interplanetary Stardate Syncrometer Scale"
authors = ["True Mark"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
