import React, { useState } from "react";
import { Alert, Box, Button, Chip, Container, Grid, Paper, Stack, TextField, Typography } from "@mui/material";
import { Link as RouterLink } from "react-router-dom";
import { colors, styles } from "./designTokens";

const sections = [["Identity", "Complete"], ["Ownership", "Complete"], ["Provenance", "In Progress"], ["Evidence", "12 items"], ["Images", "8 items"], ["Supporting Docs", "4 items"]];
const transitions = ["WORKING_COPY", "READY_FOR_REVIEW", "COMMIT_PENDING", "COMMITTED", "SEALED"];

export default function ObjectWorkbench() {
  const [state, setState] = useState("WORKING_COPY");
  const index = transitions.indexOf(state);
  const advance = () => setState(transitions[Math.min(index + 1, transitions.length - 1)]);
  return <Box sx={{ ...styles.page, minHeight: "calc(100vh - 76px)", py: { xs: 4, md: 6 } }}><Container maxWidth="xl">
    <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", md: "flex-end" }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="overline" sx={{ color: colors.gold, letterSpacing: 2 }}>OBJECT WORKBENCH · PROJECT</Typography><Typography variant="h3" sx={{ fontWeight: 800, mt: 1 }}>1967 Mustang Fastback</Typography><Typography sx={{ color: colors.mutedText, mt: 1 }}>Prepare the object record before making any authoritative claim.</Typography></Box><Chip label={state} sx={{ color: state === "SEALED" ? "#74D6A0" : colors.gold, borderColor: state === "SEALED" ? "#74D6A0" : colors.gold, background: "transparent" }} variant="outlined" /></Stack>
    <Alert severity="info" sx={{ mb: 3, background: "rgba(201,162,39,0.10)", color: colors.neutral, border: `1px solid ${colors.border}`, "& .MuiAlert-icon": { color: colors.gold } }}>The Sanctum is mutable. Uploads, notes, and drafts do not become evidence until you explicitly authorize Commit and complete the sealing transition.</Alert>
    <Grid container spacing={3}><Grid item xs={12} lg={8}><Paper sx={{ ...styles.panel, p: { xs: 2.5, md: 3 } }}><Typography variant="overline" sx={{ color: colors.mutedText, letterSpacing: 1.5 }}>OBJECT RECORD</Typography><Stack spacing={2} sx={{ mt: 2 }}><TextField label="Object title" defaultValue="1967 Mustang Fastback" fullWidth /><TextField label="Object description" defaultValue="Classic vehicle with documented family ownership history." multiline minRows={3} fullWidth /><TextField label="Ownership / creator information" placeholder="Names, roles, or claimants" fullWidth /><TextField label="Provenance notes" placeholder="Dates, transfers, supporting context" multiline minRows={3} fullWidth /></Stack><Typography variant="overline" sx={{ color: colors.mutedText, letterSpacing: 1.5, display: "block", mt: 4 }}>PENDING ACTIONS</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ mt: 1 }}><Button variant="outlined" sx={styles.secondaryButton}>Add Evidence</Button><Button variant="outlined" sx={styles.secondaryButton}>Add Image</Button><Button variant="outlined" sx={styles.secondaryButton}>Add Supporting Document</Button></Stack></Paper></Grid>
      <Grid item xs={12} lg={4}><Paper sx={{ ...styles.panel, p: 3, mb: 3 }}><Typography variant="h6" sx={{ fontWeight: 800, mb: 2 }}>Workbench status</Typography>{sections.map(([label, value]) => <Stack key={label} direction="row" justifyContent="space-between" sx={{ py: 1.4, borderBottom: `1px solid ${colors.border}` }}><Typography variant="body2">{label}</Typography><Typography variant="body2" sx={{ color: value === "Complete" ? "#74D6A0" : colors.mutedText }}>{value}</Typography></Stack>)}</Paper><Paper sx={{ ...styles.panel, p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>Authority transition</Typography><Typography variant="body2" sx={{ color: colors.mutedText, lineHeight: 1.7, mt: 1 }}>Commit is the customer-authorized action. The backend then records the committed evidence before it can be sealed.</Typography><Stack spacing={1} sx={{ mt: 2 }}>{transitions.map((step, stepIndex) => <Typography key={step} variant="caption" sx={{ color: stepIndex <= index ? colors.gold : colors.mutedText }}>{stepIndex + 1}. {step}</Typography>)}</Stack><Button fullWidth variant="contained" sx={{ ...styles.primaryButton, mt: 2 }} disabled={state === "SEALED"} onClick={advance}>{state === "WORKING_COPY" ? "Mark Ready for Review" : state === "READY_FOR_REVIEW" ? "Authorize Commit" : state === "COMMIT_PENDING" ? "Record Committed Evidence" : "Seal Immutable Record"}</Button><Button component={RouterLink} to="/sanctum" fullWidth sx={{ color: colors.mutedText, mt: 1 }}>Return to Sanctum</Button></Paper></Grid></Grid>
  </Container></Box>;
}
