import React, { useEffect, useRef, useState } from "react";
import axios from "axios";
import { Alert, Box, Button, Chip, Container, Grid, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import { Link as RouterLink, useNavigate, useParams } from "react-router-dom";
import { getUserAuthHeaders } from "./authStorage";
import { colors, styles } from "./designTokens";

const API = import.meta.env.VITE_API_URL || "http://localhost:13001";
const STATES = ["WORKING_COPY", "READY_FOR_REVIEW", "COMMIT_PENDING", "COMMITTED", "SEALED"];
const PROFILES = [["p2", "2-Layer Certificate"], ["p3", "3-Layer Certificate"], ["p5", "5-Layer Certificate"], ["p7", "7-Layer Certificate"], ["p11", "11-Layer Forensic Certificate"], ["p13", "13-Layer Elite Forensic Certificate"]];
const EMPTY = { title: "", object_type: "object", description: "", certificate_profile: "p2", ownership: "", provenance: "" };
const headers = () => ({ headers: getUserAuthHeaders() });
const detail = (error) => error?.response?.data?.detail || error.message || "Request failed.";

export default function ObjectWorkbench() {
  const { objectId } = useParams(); const navigate = useNavigate(); const picker = useRef(null);
  const [record, setRecord] = useState(null); const [form, setForm] = useState(EMPTY);
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const editable = !record || ["WORKING_COPY", "READY_FOR_REVIEW"].includes(record.state);
  const formPayload = () => ({ ...form, ownership: { summary: form.ownership }, provenance: { summary: form.provenance } });
  const load = async () => {
    if (!objectId || objectId === "new") return;
    try { const { data } = await axios.get(`${API}/api/objects/${objectId}`, headers()); setRecord(data); setForm({ title: data.title, object_type: data.object_type, description: data.description || "", certificate_profile: data.certificate_profile, ownership: data.ownership?.summary || "", provenance: data.provenance?.summary || "" }); }
    catch (requestError) { setError(detail(requestError)); }
  };
  useEffect(() => { load(); }, [objectId]); // eslint-disable-line react-hooks/exhaustive-deps
  const save = async () => { setBusy(true); setError(""); try { if (record) { const { data } = await axios.put(`${API}/api/objects/${record.id}`, formPayload(), headers()); setRecord(data); setNotice("Working copy saved."); } else { const { data } = await axios.post(`${API}/api/objects`, formPayload(), headers()); navigate(`/objects/${data.id}`, { replace: true }); } } catch (requestError) { setError(detail(requestError)); } finally { setBusy(false); } };
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file || !record) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); await axios.post(`${API}/api/objects/${record.id}/evidence`, body, headers()); await load(); setNotice(`${file.name} staged as evidence.`); } catch (requestError) { setError(detail(requestError)); } finally { event.target.value = ""; setBusy(false); } };
  const advance = async () => { if (!record) return; const target = STATES[STATES.indexOf(record.state) + 1]; if (!target) return; setBusy(true); setError(""); try { let data; if (target === "SEALED") ({ data } = await axios.post(`${API}/api/objects/${record.id}/seal`, {}, headers())); else { const confirmation = target === "COMMITTED" ? window.prompt(`Type COMMIT ${record.id} to authorize the immutable evidence commit.`) : null; if (target === "COMMITTED" && confirmation === null) return; ({ data } = await axios.post(`${API}/api/objects/${record.id}/transition`, { target_state: target, confirmation }, headers())); } setRecord(data); setNotice(target === "SEALED" ? "Object sealed in the Vault." : `${target.replaceAll("_", " ")} recorded.`); } catch (requestError) { setError(detail(requestError)); } finally { setBusy(false); } };
  const state = record?.state || "WORKING_COPY"; const stateIndex = STATES.indexOf(state);
  const action = { WORKING_COPY: "Mark Ready for Review", READY_FOR_REVIEW: "Open Commit Review", COMMIT_PENDING: "Authorize Commit", COMMITTED: "Seal Immutable Record", SEALED: "Sealed" }[state];
  return <Box sx={{ ...styles.page, minHeight: "calc(100vh - 76px)", py: { xs: 4, md: 6 } }}><Container maxWidth="xl">
    <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", md: "flex-end" }} spacing={2} sx={{ mb: 3 }}><Box><Typography variant="overline" sx={{ color: colors.gold, letterSpacing: 2 }}>OBJECT WORKBENCH · PERPETUUM</Typography><Typography variant="h3" sx={{ fontWeight: 800, mt: 1 }}>{record?.title || "New Object Record"}</Typography><Typography sx={{ color: colors.mutedText, mt: 1 }}>Draft privately; authority starts only with your reviewed Commit → Seal action.</Typography></Box><Chip label={state} variant="outlined" sx={{ color: state === "SEALED" ? "#74D6A0" : colors.gold, borderColor: state === "SEALED" ? "#74D6A0" : colors.gold }} /></Stack>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{notice && <Alert severity="success" sx={{ mb: 2 }}>{notice}</Alert>}<Alert severity="info" sx={{ mb: 3 }}>An upload is staged evidence—not authority. The Vault manifest is created only after Commit and Seal.</Alert>
    <Grid container spacing={3}><Grid item xs={12} lg={8}><Paper sx={{ ...styles.panel, p: 3 }}><Typography variant="overline" sx={{ color: colors.mutedText }}>OBJECT RECORD</Typography><Stack spacing={2} sx={{ mt: 2 }}>
      <TextField label="Object title" value={form.title} disabled={!editable} onChange={(e) => setForm({ ...form, title: e.target.value })} fullWidth /><TextField label="Object type" value={form.object_type} disabled={!editable} onChange={(e) => setForm({ ...form, object_type: e.target.value })} fullWidth /><TextField label="Object description" value={form.description} disabled={!editable} onChange={(e) => setForm({ ...form, description: e.target.value })} multiline minRows={3} fullWidth /><TextField label="Ownership / creator information" value={form.ownership} disabled={!editable} onChange={(e) => setForm({ ...form, ownership: e.target.value })} fullWidth /><TextField label="Provenance notes" value={form.provenance} disabled={!editable} onChange={(e) => setForm({ ...form, provenance: e.target.value })} multiline minRows={3} fullWidth /><TextField select label="Prime evidence profile" value={form.certificate_profile} disabled={!editable} onChange={(e) => setForm({ ...form, certificate_profile: e.target.value })} fullWidth>{PROFILES.map(([id, label]) => <MenuItem key={id} value={id}>{label}</MenuItem>)}</TextField>
    </Stack><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ mt: 3 }}><Button variant="contained" sx={styles.primaryButton} onClick={save} disabled={!editable || busy}>{record ? "Save Working Copy" : "Create Object Record"}</Button><input ref={picker} hidden type="file" onChange={upload} /><Button variant="outlined" sx={styles.secondaryButton} disabled={!record || state !== "WORKING_COPY" || busy} onClick={() => picker.current?.click()}>Stage Evidence File</Button></Stack>
    {record?.evidence?.length > 0 && <Box sx={{ mt: 3 }}><Typography variant="overline" sx={{ color: colors.mutedText }}>EVIDENCE</Typography>{record.evidence.map((item) => <Paper key={item.id} sx={{ mt: 1, p: 1.25, background: colors.surfaceSolid, border: `1px solid ${colors.border}` }}><Typography variant="body2" sx={{ fontWeight: 700 }}>{item.filename}</Typography><Typography variant="caption" sx={{ color: colors.mutedText }}>{item.state} · SHA-256 {item.sha256}</Typography></Paper>)}</Box>}</Paper></Grid>
    <Grid item xs={12} lg={4}><Paper sx={{ ...styles.panel, p: 3 }}><Typography variant="h6" sx={{ fontWeight: 800 }}>Authority transition</Typography><Typography variant="body2" sx={{ color: colors.mutedText, lineHeight: 1.7, mt: 1 }}>Commit requires typed confirmation. Seal writes the manifest under the Vault root and attaches an ISS-stamped audit event.</Typography><Stack spacing={1} sx={{ mt: 2 }}>{STATES.map((step, i) => <Typography key={step} variant="caption" sx={{ color: i <= stateIndex ? colors.gold : colors.mutedText }}>{i + 1}. {step}</Typography>)}</Stack><Button fullWidth variant="contained" sx={{ ...styles.primaryButton, mt: 2 }} disabled={!record || state === "SEALED" || busy} onClick={advance}>{action}</Button><Button component={RouterLink} to="/sanctum" fullWidth sx={{ color: colors.mutedText, mt: 1 }}>Return to Perpetuum</Button></Paper></Grid></Grid>
  </Container></Box>;
}
