import React from "react";
import { Box, Button, Chip, Container, Grid, Paper, Stack, Typography } from "@mui/material";
import { Link as RouterLink } from "react-router-dom";
import { colors, styles } from "./designTokens";
import { getActiveUser } from "./authStorage";

const projects = [
  { title: "1967 Mustang Fastback", type: "Collectible", status: "In Progress", evidence: 12, completion: "68%" },
  { title: "Calder Family Archive", type: "Heirloom", status: "Ready for Review", evidence: 24, completion: "91%" },
];

function WorkspaceCard({ title, body, action, to, accent = colors.gold }) {
  return <Paper sx={{ ...styles.panel, p: 2.5, height: "100%", borderTop: `3px solid ${accent}` }}><Typography variant="h6" sx={{ fontWeight: 800 }}>{title}</Typography><Typography variant="body2" sx={{ color: colors.mutedText, lineHeight: 1.7, mt: 1, minHeight: 48 }}>{body}</Typography><Button component={RouterLink} to={to} sx={{ color: accent, px: 0, mt: 1, fontWeight: 800 }}>{action} →</Button></Paper>;
}

export default function SanctumDashboard() {
  const user = getActiveUser();
  const name = user?.name?.split(" ")[0] || "there";
  return <Box sx={{ ...styles.page, minHeight: "calc(100vh - 76px)", py: { xs: 4, md: 6 } }}><Container maxWidth="xl">
    <Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", md: "flex-end" }} spacing={2} sx={{ mb: 4 }}><Box><Typography variant="overline" sx={{ color: colors.gold, letterSpacing: 2 }}>SECRETUM PRIVATUM — PRIVATE SANCTUM</Typography><Typography variant="h3" sx={{ fontWeight: 800, mt: 1 }}>Welcome back, {name}</Typography><Typography sx={{ color: colors.mutedText, mt: 1 }}>Your private True Mark workspace. Draft freely here; authority begins only when you commit.</Typography></Box><Button component={RouterLink} to="/objects/new" variant="contained" sx={styles.primaryButton}>Create New Project</Button></Stack>
    <Grid container spacing={2} sx={{ mb: 4 }}><Grid item xs={12} md={3}><WorkspaceCard title="Continue Working" body="Resume the object workbench where you left off." action="Open Workbench" to="/objects/1967-mustang" /></Grid><Grid item xs={12} md={3}><WorkspaceCard title="Evidence Staging" body="Temporary uploads and notes not yet committed." action="Review Staging" to="/objects/1967-mustang" accent="#9DB7C9" /></Grid><Grid item xs={12} md={3}><WorkspaceCard title="My Objects" body="Authenticated and sealed objects in your record." action="View Objects" to="/objects/1967-mustang" accent="#C98762" /></Grid><Grid item xs={12} md={3}><WorkspaceCard title="Verify" body="Check one of your records or another True Mark record." action="Open Verifier" to="/verify" accent="#74D6A0" /></Grid></Grid>
    <Grid container spacing={3}><Grid item xs={12} lg={8}><Paper sx={{ ...styles.panel, p: { xs: 2.5, md: 3 } }}><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 2 }}><Box><Typography variant="overline" sx={{ color: colors.mutedText, letterSpacing: 1.5 }}>PROJECT WORKSPACES</Typography><Typography variant="h5" sx={{ fontWeight: 800 }}>Objects in preparation</Typography></Box><Chip label="Sanctum / Mutable" sx={{ color: colors.gold, borderColor: colors.gold, background: "transparent" }} variant="outlined" /></Stack>{projects.map((project) => <Paper key={project.title} sx={{ p: 2, mb: 1.5, background: colors.surfaceSolid, border: `1px solid ${colors.border}` }}><Stack direction={{ xs: "column", sm: "row" }} spacing={2} alignItems={{ xs: "flex-start", sm: "center" }}><Box sx={{ flex: 1 }}><Typography sx={{ fontWeight: 800 }}>{project.title}</Typography><Typography variant="body2" sx={{ color: colors.mutedText }}>{project.type} · {project.evidence} evidence items · {project.completion} complete</Typography></Box><Chip label={project.status} size="small" sx={{ color: project.status === "Ready for Review" ? "#74D6A0" : colors.gold, background: "rgba(255,255,255,0.08)" }} /><Button component={RouterLink} to="/objects/1967-mustang" sx={{ color: colors.gold }}>Open</Button></Stack></Paper>)}</Paper></Grid><Grid item xs={12} lg={4}><Paper sx={{ ...styles.panel, p: 3, mb: 3 }}><Typography variant="overline" sx={{ color: colors.mutedText, letterSpacing: 1.5 }}>AUTHORITY BOUNDARY</Typography><Typography variant="h6" sx={{ fontWeight: 800, mt: 1 }}>Nothing is authoritative yet.</Typography><Typography variant="body2" sx={{ color: colors.mutedText, lineHeight: 1.7, mt: 1 }}>Your Sanctum is private and mutable. Only an explicit Commit → Seal action creates an Immutable Vault event.</Typography><Stack spacing={1} sx={{ mt: 2 }}>{["WORKING_COPY", "READY_FOR_REVIEW", "COMMIT_PENDING", "COMMITTED", "SEALED"].map((step, index) => <Stack key={step} direction="row" spacing={1.5} alignItems="center"><Box sx={{ width: 24, height: 24, borderRadius: "50%", display: "grid", placeItems: "center", background: index === 0 ? colors.gold : colors.surfaceSolid, color: index === 0 ? "#111" : colors.mutedText, fontSize: 12 }}>{index + 1}</Box><Typography variant="body2" sx={{ color: index === 0 ? colors.text : colors.mutedText }}>{step}</Typography></Stack>)}</Stack></Paper><Paper sx={{ ...styles.panel, p: 3 }}><Typography variant="overline" sx={{ color: colors.mutedText, letterSpacing: 1.5 }}>YOUR CERTIFICATES</Typography><Typography variant="h6" sx={{ fontWeight: 800, mt: 1 }}>Prime Layer profiles</Typography><Typography variant="body2" sx={{ color: colors.mutedText, lineHeight: 1.7, mt: 1 }}>Select forensic depth only after an object is ready for review.</Typography><Button component={RouterLink} to="/demo-mint" sx={{ color: colors.gold, px: 0, mt: 1 }}>View Certificate Profiles →</Button></Paper></Grid></Grid>
  </Container></Box>;
}
